name: aspnetcore_root_workflow
on:
  workflow_call:
    inputs:
      CLIENT:
        type: string
      CLIENT_ENV:
        type: string
      DOWNLOAD_PACKAGE:
        type: string
      DEPLOY_IIS:
        type: string
      SITE_NAME:
        type: string
      DOTNET_VERSION:
        type: string
      PROJECT_ROOT_DIRECTORY:
        type: string
      PROJECT_NAME:
        type: string
    secrets:
      NUGET_URL:
        required: true
      NUGET_TOKEN:
        required: true
      WEBDEPLOY_PASSWORD:
        required: true
      WEBDEPLOY_USER: 
        required: true
      SERVER_IP:
        required: true
      SERVER_PORT:
        required: true
jobs:
  Build-Package-IIS_Deploy:
    runs-on: self-hosted
    environment: 'Production'
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ inputs.DOTNET_VERSION }}
          source-url: ${{ secrets.NUGET_URL }}
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.NUGET_TOKEN }}
          
      - name: Build and publish
        run: dotnet publish ${{inputs.PROJECT_NAME}}\${{inputs.PROJECT_NAME}}.csproj --configuration Release -o ${{ env.DOTNET_ROOT}}\myapp /p:EnvironmentName=${{inputs.CLIENT}}${{inputs.CLIENT_ENV}}
  
      - name: Clean appsettings
        run: |
          cd ${{ env.DOTNET_ROOT}}\myapp
          $jsonFiles = Get-ChildItem appsettings*json
          foreach ($file in $jsonFiles) {
            if ($file.Name -inotcontains "appsettings.json") {
              if ($file.Name -inotcontains "appsettings.Config.json") {
                  if ($file.Name -inotcontains "appsettings.${{inputs.CLIENT}}${{inputs.CLIENT_ENV}}.json"){
                  #Write-Host -id 3 -activity "Removing File $($file.Name)" -Status "In progress"
                  Write-Host "$(Get-Date -f $timeStampFormat) - Removing File $($file.Name): In progress"
                  Remove-Item $file
                }
              }     
            }   
          }
          cd ..
          
      - name: Upload a Build Artifact
        if: ${{ inputs.DOWNLOAD_PACKAGE == 'true' }}
        uses: actions/upload-artifact@v2.3.1
        with:
          name: ${{inputs.PROJECT_NAME}}-${{ inputs.CLIENT }}${{ inputs.CLIENT_ENV }}
          path: ${{ env.DOTNET_ROOT}}/myapp
          
      - name: Download build artifact
        if: ${{ inputs.DOWNLOAD_PACKAGE == 'true' }}
        uses: actions/download-artifact@v2.1.0
        with:
          name: ${{inputs.PROJECT_NAME}}-${{ inputs.CLIENT }}${{ inputs.CLIENT_ENV }}
          retention-days: 1
 

      - name: Stop Application Pool
        if: ${{ inputs.DEPLOY_IIS == 'true' }}
        shell: cmd
        run: '"C:/Program Files (x86)/IIS/Microsoft Web Deploy V3/msdeploy.exe" -verb:sync -allowUntrusted -source:recycleApp -dest:recycleApp="${{ inputs.SITE_NAME }}",recycleMode="StopAppPool",computerName="https://${{ secrets.SERVER_IP }}:${{ secrets.SERVER_PORT }}/msdeploy.axd?site=${{ inputs.SITE_NAME }}",username="LUG-TCAGENT\kevin",password="${{ secrets.WEBDEPLOY_PASSWORD }}",AuthType="Basic"'

      - name: Deploy to an IIS webserver
        if: ${{ inputs.DEPLOY_IIS == 'true' }}
        shell: cmd
        run: '"C:/Program Files/IIS/Microsoft Web Deploy V3/msdeploy.exe" -verb:sync -allowUntrusted -source:contentPath="${{ env.DOTNET_ROOT}}/myapp" -dest:contentPath="${{ inputs.SITE_NAME }}",computerName="https://${{ secrets.SERVER_IP }}:${{ secrets.SERVER_PORT }}/msdeploy.axd?site=${{ inputs.SITE_NAME }}",username="${{ secrets.WEBDEPLOY_USER }}",password="${{ secrets.WEBDEPLOY_PASSWORD }}",authtype="Basic"'
      
      - name: Start Application Pool
        if: ${{ inputs.DEPLOY_IIS == 'true' }}
        shell: cmd
        run: '"C:/Program Files (x86)/IIS/Microsoft Web Deploy V3/msdeploy.exe" -verb:sync -allowUntrusted -source:recycleApp -dest:recycleApp="${{ inputs.SITE_NAME }}",recycleMode="StartAppPool",computerName="https://${{ secrets.SERVER_IP }}:${{ secrets.SERVER_PORT }}/msdeploy.axd?site=${{ inputs.SITE_NAME }}",username="LUG-TCAGENT\kevin",password="${{ secrets.WEBDEPLOY_PASSWORD }}",AuthType="Basic"'
