name: Stag CI/CD

env:
  AZURE_WEBAPP_NAME: devops002    
  AZURE_WEBAPP_PACKAGE_PATH: '.'      
  DOTNET_VERSION: '3.1.x'
  NUGET_URL: https://pkgs.dev.azure.com/laboremus-uganda/LUG/_packaging/LugNuGetFeed/nuget/v3/index.json

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
        name: 'Staging'

    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          source-url: ${{ env.NUGET_URL }}
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.NUGET_TOKEN }}
          
      - name: .Net build
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp
          
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
        name: 'Staging'
          
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: AuthAPI-Staging

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          slot-name: 'staging'
